package com.pullm.backendmonolit.entities.enums;

public enum ProductSubType {
    GROCERIES, RESTAURANT, BAR,

    CLOTHES, ACCESSORIES, BEAUTY, HOME, PETS, ELECTRONICS, GIFT,

    HEALTH_CARE, FITNESS, EDUCATION, HOBBIES, LOTTERY, HOTEL,

    RENT, UTILITY, REPAIR, FUEL, PARKING,

    PUBLIC_TRANSPORT, TAXI, FLIGHTS,

    TAXES, INSURANCE, PENALTY, CHARITY, INVESTMENT, BANKING
}
